micronaut:
  application:
    name: productsService

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/productdatabase
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password

jpa.default.properties.hibernate.hbm2ddl.auto: update

#datasources:
#  default:
#    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ''
#    schema-generate: CREATE_DROP
#    dialect: H2
#jpa.default.properties.hibernate.hbm2ddl.auto: update
